# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
      files: \.ya?ml$
    - id: end-of-file-fixer
- repo: local
  hooks:
    - id: npm-format
      name: format
      description: Runs the formatting script as specified in package.json
      entry: npm run format
      language: node
      files: \.ts$
    - id: npm-lint
      name: lint
      description: Runs the linting script as specified in package.json
      entry: npm run lint
      language: node
      files: \.ts$
